// libzm2error.h - libzm2: Z-MUSIC v2 function call library
// Copyright (C) 2026 TcbnErik

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// Under Section 7 of GPL version 3, you are granted additional
// permissions described in the GCC Runtime Library Exception, version
// 3.1, as published by the Free Software Foundation.
//
// You should have received a copy of the GNU General Public License and
// a copy of the GCC Runtime Library Exception along with this program;
// see the files COPYING and COPYING.RUNTIME respectively.  If not, see
// <http://www.gnu.org/licenses/>.

#ifndef LIBZM2ERROR_H_INCLUDED
#define LIBZM2ERROR_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

enum {
  ZM2ERR_SUCCESS = 0,
  ZM2ERR_PARAMETER_OMITTED = 1,
  ZM2ERR_INVALID_TRACK_NO = 2,
  ZM2ERR_ZMUSIC_NOT_RESIDENT = 3,
  ZM2ERR_INVALID_TRACK_BUFFER_SIZE = 4,
  ZM2ERR_TRACK_BUFFER_ALLOCATION_FAILED = 5,
  ZM2ERR_INVALID_CHANNEL_NO = 6,
  ZM2ERR_INVALID_ARRAY_TYPE = 7,
  ZM2ERR_ZMUSIC_STOPPED = 8,
  ZM2ERR_INVALID_I_COMMAND_USAGE = 9,
  ZM2ERR_NOT_A_COMPILE_COMMAND = 10,
  ZM2ERR_INVALID_AT_X_COMMAND_USAGE = 11,
  ZM2ERR_INVALID_AT_I_COMMAND_USAGE = 12,
  ZM2ERR_INVALID_RELATIVE_VOLUME = 13,
  ZM2ERR_INVALID_AT_C_COMMAND_USAGE = 14,
  ZM2ERR_INVALID_AT_A_COMMAND_USAGE = 15,
  ZM2ERR_COMMAND_IRRELEVANT_FOR_OPM_OR_ADPCM = 16,
  ZM2ERR_INVALID_AT_H_COMMAND_USAGE = 17,
  ZM2ERR_INVALID_AT_S_COMMAND_USAGE = 18,
  ZM2ERR_UNDEFINED_MML = 19,
  ZM2ERR_UNDEFINED_BRACKET_COMMAND = 20,
  ZM2ERR_MISSING_CLOSING_BRACKET = 21,
  ZM2ERR_INVALID_REPEAT_COUNT = 22,
  ZM2ERR_INVALID_REPEAT_STRUCTURE = 23,
  ZM2ERR_INVALID_REPEAT_NUMBER = 24,
  ZM2ERR_MISSING_OCTAVE_VALUE = 25,
  ZM2ERR_INVALID_OCTAVE_VALUE = 26,
  ZM2ERR_INVALID_NOTE_LENGTH = 27,
  ZM2ERR_TRACK_BUFFER_INSUFFICIENT = 28,
  ZM2ERR_INVALID_AT_B_COMMAND_USAGE = 29,
  ZM2ERR_COMMAND_IRRELEVANT_FOR_ADPCM = 30,
  ZM2ERR_INVALID_TIE_USAGE = 31,
  ZM2ERR_INVALID_T_COMMAND_USAGE = 32,
  ZM2ERR_INVALID_AT_T_COMMAND_USAGE = 33,
  ZM2ERR_MISSING_NOTE_LENGTH = 34,
  ZM2ERR_MISSING_VOLUME_VALUE = 35,
  ZM2ERR_INVALID_VOLUME_VALUE = 36,
  ZM2ERR_INVALID_AT_K_COMMAND_USAGE = 37,
  ZM2ERR_INVALID_KEYCODE = 38,
  ZM2ERR_INVALID_TONE_NUMBER = 39,
  ZM2ERR_MISSING_CLOSING_BRACE = 40,
  ZM2ERR_TOO_MANY_NOTES_IN_BRACES = 41,
  ZM2ERR_NO_NOTES_IN_BRACES = 42,
  ZM2ERR_INVALID_Q_COMMAND_USAGE = 43,
  ZM2ERR_INVALID_CONTENT_IN_BRACES = 44,
  ZM2ERR_INVALID_Y_COMMAND_USAGE = 45,
  ZM2ERR_INVALID_J_COMMAND_USAGE = 46,
  ZM2ERR_INVALID_P_COMMAND_USAGE = 47,
  ZM2ERR_INVALID_K_COMMAND_USAGE = 48,
  ZM2ERR_INVALID_CHORD_COMMAND_USAGE = 49,
  ZM2ERR_TOO_MANY_CHORDS_OR_MISSING_QUOTE = 50,
  ZM2ERR_INVALID_AT_V_COMMAND_USAGE = 51,
  ZM2ERR_INVALID_PORTAMENTO_COMMAND_USAGE = 52,
  ZM2ERR_INVALID_VELOCITY_VALUE = 53,
  ZM2ERR_INVALID_N_COMMAND_USAGE = 54,
  ZM2ERR_INVALID_AT_M_COMMAND_USAGE = 55,
  ZM2ERR_INVALID_H_COMMAND_USAGE = 56,
  ZM2ERR_INVALID_AT_Z_COMMAND_USAGE = 57,
  ZM2ERR_INVALID_PARAMETER_SPECIFICATION = 58,
  ZM2ERR_DELAY_VALUE_TOO_LONG = 59,
  ZM2ERR_ADPCM_BUFFER_INSUFFICIENT = 60,
  ZM2ERR_ADPCM_USAGE_NOT_ALLOWED = 61,
  ZM2ERR_DISK_READ_FAILED = 62,
  ZM2ERR_INVALID_W_COMMAND_USAGE = 63,
  ZM2ERR_WORK_AREA_INSUFFICIENT = 64,
  ZM2ERR_UNKNOWN_ERROR = 65,
  ZM2ERR_ZMD_VERSION_MISMATCH = 66,
  ZM2ERR_INVALID_ADPCM_CONF_USAGE = 67,
  ZM2ERR_MIDI_BOARD_NOT_INSTALLED = 68,
  ZM2ERR_INVALID_MIDI_PARAMETER = 69,
  ZM2ERR_INVALID_PARAMETER_VALUE = 70,
  ZM2ERR_FILE_WRITE_FAILED = 71,
  ZM2ERR_INVALID_X_COMMAND_USAGE = 72,
  ZM2ERR_MIDI_DATA_NOT_RECEIVED = 73,
  ZM2ERR_INVALID_WAVEFORM_NUMBER = 74,
  ZM2ERR_INVALID_M_COMMAND_USAGE = 75,
  ZM2ERR_INVALID_WAVEFORM_COMMAND_USAGE = 76,
  ZM2ERR_INVALID_SEMICOLON_COMMAND_USAGE = 77,
  ZM2ERR_INVALID_YEN_COMMAND_USAGE = 78,
  ZM2ERR_INVALID_QUESTION_COMMAND_USAGE = 79,
  ZM2ERR_INVALID_AT_F_COMMAND_USAGE = 80,
  ZM2ERR_INVALID_AT_G_COMMAND_USAGE = 81,
  ZM2ERR_INVALID_AT_Y_COMMAND_USAGE = 82,
  ZM2ERR_INVALID_AT_E_COMMAND_USAGE = 83,
};

#ifdef __cplusplus
}
#endif

#endif
